### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "DOMDocument" not found in /home/jm

### ISSUE THREAD

**Issue by jminexa** [Savvii/openprovider-zone-export#1]
Hi,

I'm getting this error upon excecuting. (its probably me)

PHP Fatal error:  Uncaught Error: Class "DOMDocument" not found in /home/jm/openprovider-zone-export/lib/API.php:386
Stack trace:
#0 /home/jm/openprovider-zone-export/lib/API.php(380): OP_Request->_getRequest()
#1 /home/jm/openprovider-zone-export/lib/API.php(46): OP_Request->getRaw()
#2 /home/jm/openprovider-zone-export/get_zones.php(156): OP_API->process()
#3 /home/jm/openprovider-zone-export/get_zones.php(50): GetAllTool->getApiDomainList()
#4 /home/jm/openprovider-zone-export/get_zones.php(253): GetAllTool->run()
#5 {main}
  thrown in /home/jm/openprovider-zone-export/lib/API.php on line 386

**Comment by jminexa** [comment]
PHP8.1 is the issue! :D 
I'll reinstall my Ubuntu to 22.04, eagerly installed 22.10 :+1:

**Comment by jminexa** [comment]
Installed 22.04, but running in more or less the same issue badcow/dns is a php8.0+ dependencie. 
So I was able to install php7.4 but composer install wouldn't run as I need 8.0 for the dependencie.

When I run ./get-zones with php8 i'm running again into the error above :(
When i run ./get-zones with php7.4 it says I need at least 8.0 due to the badcow/dns

#halp

**Comment by jeroenvermeulen** [comment]
Yes, the requirements say PHP 8.0 or greater.
I will test on Ubuntu Jammy (22.04) later.
If you manage to find the issue, please let me know.

**Comment by jeroenvermeulen** [comment]
You are missing the DOM extension. 
You can probably install it using:

```
sudo apt-get install php-xml
```

I have updated the `composer.json` so you get a notice when it is missing.

**Comment by jminexa** [comment]
Sweet! Will test it tomorrow! Slaap se 😊

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________


​
​Met vriendelijke groet, cordialement, best regards,
​
​
Jordy Minnebo
Network Consultant
Exabyte BV
t: +3233690120
a: Pedro Colomalaan 2, 2880 Bornem
w: www.exabyte.be  e: ***@***.***
​
Van: Jeroen Vermeulen ***@***.***>
Verzonden: Thursday, October 27, 2022 10:27:27 PM
Aan: Savvii/openprovider-zone-export ***@***.***>
CC: Jordy Minnebo ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Savvii/openprovider-zone-export] PHP Fatal error: Uncaught Error: Class "DOMDocument" not found in /home/jm (Issue #1)


You are missing the DOM extension.
You can probably install it using:

sudo apt-get install php-xml


I have updated the composer.json so you get a notice when it is missing.

**Comment by jminexa** [comment]
Got it working, after installing all the requirted stuff, I still was getting some error. But by turning debug on, I found out my API Auth failed. 

All is working and exporting right at this moment as we speak ;)

**Comment by jeroenvermeulen** [comment]
I have [fixed](https://github.com/Savvii/openprovider-zone-export/commit/125fd14b2975e0325c793ee1c2c120b99dea6031) the crash when the auth is wrong. Now the error is more clear:

```
Calling API to get domain list, offset 0 limit 50
PHP Fatal error:  Uncaught Exception: Authentication/Authorization Failed in /path/to/openprovider-zone-export/get_zones.php:158
Stack trace:
#0 /path/to/openprovider-zone-export/get_zones.php(50): GetAllTool->getApiDomainList()
#1 /path/to/openprovider-zone-export/get_zones.php(253): GetAllTool->run()
#2 {main}
  thrown in /path/to/openprovider-zone-export/get_zones.php on line 158
  ```
